model:
  name: resnet18

task:
  name: cifar_demo
  dataloader:
    train:
      batch_size: 16

optimizer:
  name: adam

lr_scheduler:
  name: linear_100k

trainer:
  name: ddp

logger:
  - name: stdout
  - name: tensorboard
