model:
  name: resnet18

task:
  name: cifar_demo
  finished:
    max_steps: 100_000
  dataloader:
    train:
      batch_size: 16

optimizer:
  name: adam

lr_scheduler:
  name: linear

trainer:
  name: ddp

logger:
  - name: stdout
  - name: tensorboard
