name: Python Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  run-all-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]
    steps:
      - name: Fail for all draft PRs
        if: github.event.pull_request.draft
        run: |
          exit 1
      - name: Check out environment
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('Makefile') }}
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge
          channel-priority: true
          auto-activate-base: true
          activate-environment: ml-${{ matrix.python-version }}
          python-version: ${{ matrix.python-version }}
          use-only-tar-bz2: true
          use-mamba: true
      - name: Install
        run: |
          make install-deps
          make install-format-deps
          make install
      - name: Static checks
        run: |
          make static-checks
      - name: Unit tests
        run: |
          make test
